CREATE TABLE users (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  email VARCHAR NOT NULL UNIQUE,
  name VARCHAR NOT NULL,
  cpf VARCHAR NOT NULL UNIQUE,
  birthday DATE NOT NULL,
  photo TEXT,
  state_address VARCHAR NOT NULL,
  city VARCHAR,
  phone_number VARCHAR NOT NULL UNIQUE,
  gender VARCHAR,
  password_encrypted VARCHAR NOT NULL
);

CREATE TABLE doctors (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  crm_uf VARCHAR NOT NULL,
  crm_number VARCHAR NOT NULL UNIQUE,
  experience_time VARCHAR,
  street VARCHAR NOT NULL,
  address_number SMALLINT NOT NULL,
  address_complement VARCHAR,
  appointment_price REAL,
  description VARCHAR,
  remote_appointments BOOLEAN NOT NULL DEFAULT true,
  user_id SMALLINT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  insurances SMALLINT[],
  specialty TEXT
);

CREATE TABLE insurances (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE patients (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  insurance SMALLINT REFERENCES insurances(id),
  user_id SMALLINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE appointments (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  doctor_id SMALLINT NOT NULL UNIQUE REFERENCES doctors(id) ON DELETE CASCADE ON UPDATE CASCADE,
  patient_id SMALLINT UNIQUE REFERENCES patients(id) ON DELETE SET NULL ON UPDATE CASCADE,
  date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  rate SMALLINT,
  observation VARCHAR
);

CREATE TABLE medical_records (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  patient_id SMALLINT NOT NULL UNIQUE REFERENCES patients(id) ON DELETE CASCADE ON UPDATE CASCADE,
  weight SMALLINT,
  height SMALLINT,
  skin_color VARCHAR,
  heart_disease BOOLEAN,
  diabetes BOOLEAN,
  smoker BOOLEAN,
  cancer_history BOOLEAN,
  drinker BOOLEAN,
  disabilities BOOLEAN,
  allergies VARCHAR[],
  medicines VARCHAR[],
  observations VARCHAR
);

INSERT INTO insurances (name) VALUES
  ('Unimed'),
  ('Bradesco Saúde'),
  ('SulAmérica'),
  ('Amil'),
  ('NotreDame Intermédica');
