BEGIN;

CREATE TABLE IF NOT EXISTS public.medical_specialties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medical_specialty VARCHAR NOT NULL,
  access_frequency BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT medical_specialties_specialty_name_key UNIQUE (medical_specialty)
);

INSERT INTO public.medical_specialties (medical_specialty) VALUES
  ('Cardiologia'),
  ('Clínica Geral'),
  ('Dermatologia'),
  ('Ginecologia'),
  ('Neurologia'),
  ('Ortopedia'),
  ('Pediatria'),
  ('Psiquiatria')
ON CONFLICT (medical_specialty) DO NOTHING;

INSERT INTO public.medical_specialties (medical_specialty)
SELECT DISTINCT specialty
FROM public.doctors
WHERE specialty IS NOT NULL
ON CONFLICT (medical_specialty) DO NOTHING;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'doctors_specialty_fkey'
      AND conrelid = 'public.doctors'::regclass
  ) THEN
    ALTER TABLE public.doctors
      ADD CONSTRAINT doctors_specialty_fkey
      FOREIGN KEY (specialty)
      REFERENCES public.medical_specialties (medical_specialty)
      ON DELETE SET NULL
      ON UPDATE CASCADE;
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS doctors_specialty_idx
  ON public.doctors (specialty);

COMMIT;
