BEGIN;

CREATE TABLE IF NOT EXISTS public.questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS questions_created_at_id_idx
  ON public.questions (created_at DESC, id DESC);

COMMIT;