BEGIN;

CREATE TABLE IF NOT EXISTS public.answers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE ON UPDATE CASCADE,
  doctor_id SMALLINT NOT NULL REFERENCES public.doctors(id) ON DELETE CASCADE ON UPDATE CASCADE,
  answer TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT answers_question_doctor_key UNIQUE (question_id, doctor_id)
);

CREATE INDEX IF NOT EXISTS answers_question_created_at_idx
  ON public.answers (question_id, created_at DESC);
CREATE INDEX IF NOT EXISTS answers_doctor_id_idx ON public.answers (doctor_id);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    EXECUTE 'REVOKE ALL ON TABLE public.questions, public.answers FROM anon';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'REVOKE ALL ON TABLE public.questions, public.answers FROM authenticated';
  END IF;
END
$$;

COMMIT;